logging:
  level:
    root: off
spring:
  datasource:
    url: jdbc:mysql://liziyun.work:3306/message?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&useTimezone=true&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false&useSSL=false
    username: root
    password: lixiaodou1031!+-
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 52013
